# Copyright 2026 EOAP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-07-22T21:07:16+00:00

from __future__ import annotations
from pydantic import BaseModel
from enum import Enum
from pydantic import AnyUrl, AwareDatetime, ConfigDict, Field
from typing import Annotated, Any, Literal


class HealthyStatus(Enum):
    """
    Case-insensitive service health status.

    Acceptable aliases:
    - `pass`;
    - `ok` to support Node's Terminus;
    - `up` for Java's SpringBoot.

    """

    PASS = "pass"
    OK = "ok"
    UP = "up"


class UnhealthyStatus(Enum):
    """
    Case-insensitive service unhealth status.

    Acceptable aliases:
    - `fail`;
    - `error` to support Node's Terminus;
    - `down` for Java's SpringBoot.

    """

    FAIL = "fail"
    ERROR = "error"
    DOWN = "down"


class ComponentHealth(BaseModel):
    """
    Health details for one instance or observation of a dependency or
    sub-component. Additional implementation-defined keys are permitted.

    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    component_id: Annotated[str | None, Field(alias="componentId")] = None
    """
    Unique identifier of a sub-component instance.
    """
    component_type: Annotated[
        str | None, Field(alias="componentType", examples=["datastore"])
    ] = None
    """
    Component type. Suggested values include `component`, `datastore`,
    and `system`; standard terms or URIs may also be used.

    """
    observed_value: Annotated[Any | None, Field(alias="observedValue")] = None
    """
    Any valid JSON value observed by the health check.
    """
    observed_unit: Annotated[
        str | None, Field(alias="observedUnit", examples=["ms"])
    ] = None
    """
    Unit for `observedValue`, preferably a standard term, abbreviation,
    or URI.

    """
    status: HealthyStatus | UnhealthyStatus | Any | None = None
    affected_endpoints: Annotated[
        list[str] | None,
        Field(
            alias="affectedEndpoints",
            examples=[["/users/{userId}", "/customers/{customerId}/status"]],
        ),
    ] = None
    """
    URI Templates for API endpoints affected by this observation. It
    should be omitted when the component status is `pass`.

    """
    time: AwareDatetime | None = None
    """
    Time at which the observed value was recorded.
    """
    output: str | None = None
    """
    Raw error or diagnostic output for the component. It should be
    omitted when the component status is `pass`.

    """
    links: dict[str, AnyUrl] | None = None


class BaseHealthResponse(BaseModel):
    """
    A service health representation.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    version: str | None = None
    """
    Public version of the service.
    """
    release_id: Annotated[str | None, Field(alias="releaseId")] = None
    """
    Identifier of the deployed service release.
    """
    notes: list[str] | None = None
    """
    Notes relevant to the current health state.
    """
    output: str | None = None
    """
    Raw error or diagnostic output for `fail` or `warn`. It should be
    omitted when status is `pass`.

    """
    checks: Annotated[dict[str, list[ComponentHealth]] | None, Field(min_length=1)] = (
        None
    )
    links: dict[str, AnyUrl] | None = None
    service_id: Annotated[str | None, Field(alias="serviceId")] = None
    """
    Unique service identifier within the application scope.
    """
    description: str | None = None
    """
    Human-readable description of the service.
    """


class HealthyResponse(BaseHealthResponse):
    """
    A service health representation.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    status: HealthyStatus = HealthyStatus.UP


class UnhealthyResponse(BaseHealthResponse):
    """
    A service health representation.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    status: UnhealthyStatus = UnhealthyStatus.FAIL


class WarnResponse(BaseHealthResponse):
    """
    A service health representation.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    status: Literal["warn"] = "warn"
    """
    Case-insensitive service healthy, with some concerns, status.

    """
